"""Initial schema

Revision ID: 0ecea1034870
Revises: 
Create Date: 2025-11-12 16:14:33.371779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ecea1034870'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMINISTRATOR', 'COUNSELOR', 'SYSTEM_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('students',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('student_id_external', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id_external')
    )
    op.create_index(op.f('ix_students_grade_level'), 'students', ['grade_level'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('teachers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_table('audio_files',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('recording_date', sa.String(length=50), nullable=True),
    sa.Column('transcription_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_student_id'), 'audio_files', ['student_id'], unique=False)
    op.create_index(op.f('ix_audio_files_transcription_status'), 'audio_files', ['transcription_status'], unique=False)
    op.create_table('game_sessions',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mission_id', sa.String(length=100), nullable=True),
    sa.Column('game_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_session_student_started', 'game_sessions', ['student_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_game_sessions_started_at'), 'game_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_game_sessions_student_id'), 'game_sessions', ['student_id'], unique=False)
    op.create_table('rubric_assessments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('skill_type', sa.Enum('EMPATHY', 'ADAPTABILITY', 'PROBLEM_SOLVING', 'SELF_REGULATION', 'RESILIENCE', 'COMMUNICATION', 'COLLABORATION', name='skilltype'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rubric_assessment_student_skill_created', 'rubric_assessments', ['student_id', 'skill_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_rubric_assessments_skill_type'), 'rubric_assessments', ['skill_type'], unique=False)
    op.create_index(op.f('ix_rubric_assessments_student_id'), 'rubric_assessments', ['student_id'], unique=False)
    op.create_index(op.f('ix_rubric_assessments_teacher_id'), 'rubric_assessments', ['teacher_id'], unique=False)
    op.create_table('skill_assessments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_type', sa.Enum('EMPATHY', 'ADAPTABILITY', 'PROBLEM_SOLVING', 'SELF_REGULATION', 'RESILIENCE', 'COMMUNICATION', 'COLLABORATION', name='skilltype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('feature_importance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_assessment_student_skill_created', 'skill_assessments', ['student_id', 'skill_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_skill_assessments_skill_type'), 'skill_assessments', ['skill_type'], unique=False)
    op.create_index(op.f('ix_skill_assessments_student_id'), 'skill_assessments', ['student_id'], unique=False)
    op.create_table('teacher_student',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'student_id')
    )
    op.create_table('behavioral_features',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('task_completion_rate', sa.Float(), nullable=False),
    sa.Column('time_efficiency', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=False),
    sa.Column('distraction_resistance', sa.Float(), nullable=False),
    sa.Column('focus_duration', sa.Float(), nullable=False),
    sa.Column('collaboration_indicators', sa.Integer(), nullable=False),
    sa.Column('leadership_indicators', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_features_student_id'), 'behavioral_features', ['student_id'], unique=False)
    op.create_table('evidence',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.Enum('LINGUISTIC', 'BEHAVIORAL', 'CONTEXTUAL', name='evidencetype'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['skill_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_assessment_id'), 'evidence', ['assessment_id'], unique=False)
    op.create_table('game_telemetry',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('mission_id', sa.String(length=100), nullable=True),
    sa.Column('choice_made', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_event_type_timestamp', 'game_telemetry', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_telemetry_student_timestamp', 'game_telemetry', ['student_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_game_telemetry_event_type'), 'game_telemetry', ['event_type'], unique=False)
    op.create_index(op.f('ix_game_telemetry_mission_id'), 'game_telemetry', ['mission_id'], unique=False)
    op.create_index(op.f('ix_game_telemetry_session_id'), 'game_telemetry', ['session_id'], unique=False)
    op.create_index(op.f('ix_game_telemetry_student_id'), 'game_telemetry', ['student_id'], unique=False)
    op.create_index(op.f('ix_game_telemetry_timestamp'), 'game_telemetry', ['timestamp'], unique=False)
    op.create_table('transcripts',
    sa.Column('audio_file_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('word_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_id')
    )
    op.create_index(op.f('ix_transcripts_student_id'), 'transcripts', ['student_id'], unique=False)
    op.create_table('linguistic_features',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('empathy_markers', sa.Integer(), nullable=False),
    sa.Column('problem_solving_language', sa.Integer(), nullable=False),
    sa.Column('perseverance_indicators', sa.Integer(), nullable=False),
    sa.Column('social_processes', sa.Integer(), nullable=False),
    sa.Column('cognitive_processes', sa.Integer(), nullable=False),
    sa.Column('positive_sentiment', sa.Float(), nullable=False),
    sa.Column('negative_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_sentence_length', sa.Float(), nullable=False),
    sa.Column('syntactic_complexity', sa.Float(), nullable=False),
    sa.Column('word_embeddings', sa.JSON(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id')
    )
    op.create_index(op.f('ix_linguistic_features_student_id'), 'linguistic_features', ['student_id'], unique=False)
    # Note: Removed drop_table commands for part_config and part_config_sub
    # These tables are part of the pg_partman extension and should not be dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed part_config and part_config_sub table recreation
    # These tables are part of the pg_partman extension and should not be managed by Alembic
    op.drop_index(op.f('ix_linguistic_features_student_id'), table_name='linguistic_features')
    op.drop_table('linguistic_features')
    op.drop_index(op.f('ix_transcripts_student_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_game_telemetry_timestamp'), table_name='game_telemetry')
    op.drop_index(op.f('ix_game_telemetry_student_id'), table_name='game_telemetry')
    op.drop_index(op.f('ix_game_telemetry_session_id'), table_name='game_telemetry')
    op.drop_index(op.f('ix_game_telemetry_mission_id'), table_name='game_telemetry')
    op.drop_index(op.f('ix_game_telemetry_event_type'), table_name='game_telemetry')
    op.drop_index('idx_telemetry_student_timestamp', table_name='game_telemetry')
    op.drop_index('idx_telemetry_event_type_timestamp', table_name='game_telemetry')
    op.drop_table('game_telemetry')
    op.drop_index(op.f('ix_evidence_assessment_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_behavioral_features_student_id'), table_name='behavioral_features')
    op.drop_table('behavioral_features')
    op.drop_table('teacher_student')
    op.drop_index(op.f('ix_skill_assessments_student_id'), table_name='skill_assessments')
    op.drop_index(op.f('ix_skill_assessments_skill_type'), table_name='skill_assessments')
    op.drop_index('idx_skill_assessment_student_skill_created', table_name='skill_assessments')
    op.drop_table('skill_assessments')
    op.drop_index(op.f('ix_rubric_assessments_teacher_id'), table_name='rubric_assessments')
    op.drop_index(op.f('ix_rubric_assessments_student_id'), table_name='rubric_assessments')
    op.drop_index(op.f('ix_rubric_assessments_skill_type'), table_name='rubric_assessments')
    op.drop_index('idx_rubric_assessment_student_skill_created', table_name='rubric_assessments')
    op.drop_table('rubric_assessments')
    op.drop_index(op.f('ix_game_sessions_student_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_started_at'), table_name='game_sessions')
    op.drop_index('idx_game_session_student_started', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_audio_files_transcription_status'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_student_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_grade_level'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
